/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["AppController_getHello"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Retrieve authenticated user profile information
     */
    get: operations["UserController_findMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update user profile
     * @description Update current user profile information
     */
    patch: operations["UserController_updateProfile"];
    trace?: never;
  };
  "/api/v1/users/me/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload user avatar
     * @description Upload a new avatar image for the current user (max 5MB)
     */
    post: operations["UserController_uploadAvatar"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a new user
     * @description Create a new user account and send verification email
     */
    post: operations["AuthController_register"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User login
     * @description Login with email and password to receive JWT token
     */
    post: operations["AuthController_login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request password reset
     * @description Send password reset link to user email
     */
    post: operations["AuthController_forgotPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password
     * @description Set new password using reset token
     */
    post: operations["AuthController_resetPassword"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/verify-email": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify email
     * @description Verify user email using token sent to email
     */
    post: operations["AuthController_verifyEmail"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user workspaces
     * @description Retrieve all workspaces for the current user with optional filtering
     */
    get: operations["WorkspaceController_findAll"];
    put?: never;
    /**
     * Create new workspace
     * @description Create a new workspace for the current user
     */
    post: operations["WorkspaceController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete workspace
     * @description Remove a workspace permanently
     */
    delete: operations["WorkspaceController_removeWorkspace"];
    options?: never;
    head?: never;
    /**
     * Update workspace
     * @description Update workspace information
     */
    patch: operations["WorkspaceController_update"];
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get workspace members
     * @description Retrieve all members of a workspace
     */
    get: operations["WorkspaceController_findMembers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}/members/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member from workspace
     * @description Remove a member from a workspace
     */
    delete: operations["WorkspaceController_remove"];
    options?: never;
    head?: never;
    /**
     * Update member role
     * @description Change member role to admin, member, or viewer
     */
    patch: operations["WorkspaceController_updateMembersPrivilages"];
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}/invitations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invite member to workspace
     * @description Send invitation to user to join workspace
     */
    post: operations["WorkspaceController_inviteMember"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspaces/accept-invitation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept workspace invitation
     * @description Accept an invitation to join a workspace
     */
    post: operations["WorkspaceController_acceptInvitation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspace-member": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["WorkspaceMemberController_findAll"];
    put?: never;
    post: operations["WorkspaceMemberController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/workspace-member/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations["WorkspaceMemberController_remove"];
    options?: never;
    head?: never;
    patch: operations["WorkspaceMemberController_update"];
    trace?: never;
  };
  "/api/v1/workspaces/{workspaceId}/boards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all boards in workspace
     * @description Retrieve paginated list of boards in a workspace with optional filtering
     */
    get: operations["BoardController_findAll"];
    put?: never;
    /**
     * Create a new board
     * @description Create a new board in a workspace
     */
    post: operations["BoardController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}/columns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all columns in board
     * @description Retrieve all columns for a specific board
     */
    get: operations["ColumnController_findAll"];
    put?: never;
    /**
     * Create new column
     * @description Create a new column in a board
     */
    post: operations["ColumnController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all tasks in a board
     * @description Retrieve paginated list of tasks for a specific board
     */
    get: operations["TaskController_findAll"];
    put?: never;
    /**
     * Create task in board
     * @description Create a new task directly in a board
     */
    post: operations["ColumnController_createTasks"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive board
     * @description Archive a board to hide it from active boards
     */
    post: operations["ColumnController_archiveBoard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore archived board
     * @description Restore an archived board back to active
     */
    post: operations["ColumnController_restoreBoard"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/boards/{boardId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete board
     * @description Remove a board permanently
     */
    delete: operations["ColumnController_removeBoard"];
    options?: never;
    head?: never;
    /**
     * Update board
     * @description Update board information
     */
    patch: operations["ColumnController_updateBoard"];
    trace?: never;
  };
  "/api/v1/boards/{boardId}/columns/{columnId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete column
     * @description Remove a column from a board
     */
    delete: operations["ColumnController_remove"];
    options?: never;
    head?: never;
    /**
     * Update column
     * @description Update column information
     */
    patch: operations["ColumnController_update"];
    trace?: never;
  };
  "/api/v1/boards/{boardId}/columns/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Reorder columns
     * @description Change the order of columns in a board
     */
    put: operations["ColumnController_reOrderColumn"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task details
     * @description Retrieve detailed information about a specific task
     */
    get: operations["TaskController_findOne"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/{taskId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete task
     * @description Remove a task completely
     */
    delete: operations["TaskController_remove"];
    options?: never;
    head?: never;
    /**
     * Update task
     * @description Update task information like title, description, priority, etc.
     */
    patch: operations["TaskController_update"];
    trace?: never;
  };
  "/api/v1/tasks/{taskId}/assignees": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Assign users to task
     * @description Add one or more users as assignees to a task
     */
    post: operations["TaskController_assignTask"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{taskId}/assignees/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Unassign user from task
     * @description Remove a user from task assignees
     */
    delete: operations["TaskController_unassignTask"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{taskId}/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Move task to different column
     * @description Move a task from one column to another
     */
    patch: operations["TaskController_moveTask"];
    trace?: never;
  };
  "/api/v1/tasks/{taskId}/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task comments
     * @description Retrieve paginated list of comments for a task
     */
    get: operations["CommentController_findAll"];
    put?: never;
    /**
     * Create comment on task
     * @description Add a new comment to a task
     */
    post: operations["CommentController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/comments/{commentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete comment
     * @description Remove a comment
     */
    delete: operations["CommentController_remove"];
    options?: never;
    head?: never;
    /**
     * Update comment
     * @description Update an existing comment
     */
    patch: operations["CommentController_update"];
    trace?: never;
  };
  "/api/v1/tasks/{taskId}/attachments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task attachments
     * @description Retrieve all attachments for a task
     */
    get: operations["AttachmentController_findAll"];
    put?: never;
    /**
     * Upload task attachment
     * @description Upload a file attachment to a task (max 10MB)
     */
    post: operations["AttachmentController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/attachments/{attachmentId}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download attachment
     * @description Download an attachment file
     */
    get: operations["AttachmentController_downloadAttachment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["AttachmentController_update"];
    trace?: never;
  };
  "/api/v1/attachments/attachmentId": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete attachment
     * @description Remove an attachment file
     */
    delete: operations["AttachmentController_remove"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tag": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all tags
     * @description Retrieve all available tags
     */
    get: operations["TagController_findAll"];
    put?: never;
    /**
     * Create tag
     * @description Create a new tag for organizing tasks
     */
    post: operations["TagController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create activity
     * @description Log a new activity
     */
    post: operations["ActivityController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/activity/tasks/{taskId}/activity": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get task activity log
     * @description Retrieve activity log for a specific task
     */
    get: operations["ActivityController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/mark-all-read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mark all notifications as read
     * @description Mark all user notifications as read
     */
    post: operations["NotificationController_markAllAsRead"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user notifications
     * @description Retrieve all notifications for the current user
     */
    get: operations["NotificationController_findAll"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/notifications/{notification_id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Mark notification as read
     * @description Mark a specific notification as read
     */
    patch: operations["NotificationController_markAsRead"];
    trace?: never;
  };
  "/api/v1/task-assignee": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TaskAssigneeController_findAll"];
    put?: never;
    post: operations["TaskAssigneeController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/task-tags": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TaskTagsController_findAll"];
    put?: never;
    post: operations["TaskTagsController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/task-watcher": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["TaskWatcherController_findAll"];
    put?: never;
    post: operations["TaskWatcherController_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Global search
     * @description Search for tasks, comments, attachments across the workspace
     */
    get: operations["SearchController_globalSearch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    UpdateProfileDto: {
      /**
       * @description First name
       * @example John
       */
      firstname?: string;
      /**
       * @description Last name
       * @example Doe
       */
      lastname?: string;
      /**
       * @description User bio
       * @example Software developer
       */
      bio?: string;
      /**
       * @description Current password (required if changing password)
       * @example currentpass123
       */
      currentPassword?: string;
      /**
       * @description New password
       * @example newpass123
       */
      newPassword?: string;
    };
    CreateUserDto: {
      /**
       * @description firstname of user account
       * @example firstname
       */
      firstname: string;
      /**
       * @description lastname of user account
       * @example lastname
       */
      lastname: string;
      /**
       * @description email of user account
       * @example email@google.com
       */
      email: string;
      /**
       * @description password of user account
       * @example password
       */
      password: string;
    };
    LoginDto: {
      /**
       * @description email of user
       * @example test@gmail.com
       */
      email: string;
      /**
       * @description password of user
       * @example 123123123
       */
      password: string;
    };
    CreateWorkspaceDto: {
      /** @example Marketing team */
      name: string;
      /** @example description of workspace */
      description: string;
      /**
       * @description set the workspace to false
       * @default false
       */
      isPrivate: boolean;
    };
    UpdateWorkspaceDto: {
      /** @example Marketing team */
      name?: string;
      /** @example description of workspace */
      description?: string;
      /**
       * @description set the workspace to false
       * @default false
       */
      isPrivate: boolean;
    };
    CreateInvitationDto: {
      /**
       * @description Email of user to invite
       * @example user@example.com
       */
      email: string;
      /**
       * @description Role for invited user
       * @example member
       * @enum {string}
       */
      role: "admin" | "member" | "viewer";
      /**
       * @description Custom message for invitation
       * @example Join us!
       */
      message?: string;
    };
    CreateWorkspaceMemberDto: Record<string, never>;
    UpdateWorkspaceMemberDto: Record<string, never>;
    CreateBoardDto: {
      /** @example Board 1 */
      name: string;
      /** @example Board 1 description */
      description: string;
      /**
       * @description should be hex color
       * @example #666
       */
      backgroundColor: string;
      /**
       * @example PUBLIC
       * @enum {string}
       */
      visibility: "PUBLIC" | "PRIVATE" | "WORKSPACE";
    };
    CreateColumnDto: {
      /**
       * @description Column name
       * @example To Do
       */
      name: string;
    };
    CreateTaskDto: {
      /**
       * @description task title
       * @example task 1
       */
      title: string;
      /**
       * @description task description
       * @example task 1 description
       */
      description?: string;
      /**
       * @description column id that you will create task in
       * @example uuid
       */
      columnId?: string;
      /**
       * @description priority of task
       * @default medium
       * @example high
       */
      priority: string;
      /**
       * @description due date of task
       * @example 2026-04-12T16:59:56.434Z
       */
      dueDate?: string;
      /**
       * @description estimated Hours of the task to be done
       * @example 50
       */
      estimatedHours?: number;
      /**
       * @description array of assignee ids to assign users to that task
       * @example [
       *       "uuid"
       *     ]
       */
      assigneeIds?: string[];
      /**
       * @description array of tag ids to give tags to that task
       * @example [
       *       "uuid"
       *     ]
       */
      tagIds?: string[];
    };
    UpdateBoardDto: {
      /** @example Board 1 */
      name?: string;
      /** @example Board 1 description */
      description?: string;
      /**
       * @description should be hex color
       * @example #666
       */
      backgroundColor?: string;
      /**
       * @example PUBLIC
       * @enum {string}
       */
      visibility?: "PUBLIC" | "PRIVATE" | "WORKSPACE";
    };
    UpdateColumnDto: {
      /**
       * @description Column name
       * @example To Do
       */
      name?: string;
    };
    ReOrderColumnDto: {
      /**
       * @description Column UUID to reorder
       * @example uuid
       */
      columnId: string;
      /**
       * @description New position for the column
       * @example 2
       */
      newPosition: number;
    };
    UpdateTaskDto: {
      /**
       * @description task title
       * @example task 1
       */
      title?: string;
      /**
       * @description task description
       * @example task 1 description
       */
      description?: string;
      /**
       * @description column id that you will create task in
       * @example uuid
       */
      columnId?: string;
      /**
       * @description priority of task
       * @default medium
       * @example high
       */
      priority: string;
      /**
       * @description due date of task
       * @example 2026-04-12T16:59:56.434Z
       */
      dueDate?: string;
      /**
       * @description estimated Hours of the task to be done
       * @example 50
       */
      estimatedHours?: number;
      /**
       * @description array of assignee ids to assign users to that task
       * @example [
       *       "uuid"
       *     ]
       */
      assigneeIds?: string[];
      /**
       * @description array of tag ids to give tags to that task
       * @example [
       *       "uuid"
       *     ]
       */
      tagIds?: string[];
    };
    AssignUsersToTaskDto: {
      /**
       * @description Array of user IDs to assign to task
       * @example [
       *       "uuid1",
       *       "uuid2"
       *     ]
       */
      assigneeIds: string[];
    };
    MoveTaskDto: {
      /**
       * @description Target column UUID
       * @example uuid
       */
      columnId: string;
      /**
       * @description New position in column
       * @example 0
       */
      position: number;
    };
    CreateCommentDto: {
      /**
       * @description Comment content
       * @example This task looks good
       */
      content: string;
      /**
       * @description Array of user IDs mentioned in comment
       * @example [
       *       "uuid1",
       *       "uuid2"
       *     ]
       */
      mentionedUserIds?: string[];
    };
    UpdateCommentDto: {
      /**
       * @description Comment content
       * @example This task looks good
       */
      content?: string;
      /**
       * @description Array of user IDs mentioned in comment
       * @example [
       *       "uuid1",
       *       "uuid2"
       *     ]
       */
      mentionedUserIds?: string[];
    };
    UpdateAttachmentDto: Record<string, never>;
    CreateTagDto: {
      /**
       * @description Tag name
       * @example Urgent
       */
      name: string;
      /**
       * @description Tag color in hex format
       * @example #FF0000
       */
      color: string;
    };
    CreateActivityDto: {
      /**
       * @description Activity action or description
       * @example Task updated
       */
      action: string;
    };
    CreateTaskAssigneeDto: Record<string, never>;
    CreateTaskTagDto: Record<string, never>;
    CreateTaskWatcherDto: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_getHello: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_findMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProfileDto"];
      };
    };
    responses: {
      /** @description Profile updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserController_uploadAvatar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          avatar?: string;
        };
      };
    };
    responses: {
      /** @description Avatar uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description File too large or invalid format */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUserDto"];
      };
    };
    responses: {
      /** @description User registered successfully. Verification email sent. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginDto"];
      };
    };
    responses: {
      /** @description Login successful. Returns JWT token */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_forgotPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @example user@example.com */
          email?: string;
        };
      };
    };
    responses: {
      /** @description Reset link sent to email */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email is required */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_resetPassword: {
    parameters: {
      query: {
        /** @description Reset token from email */
        token: string;
        /** @description User ID */
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @example newPassword123 */
          password?: string;
        };
      };
    };
    responses: {
      /** @description Password reset successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid token or password not provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_verifyEmail: {
    parameters: {
      query: {
        /** @description Verification token from email */
        token: string;
        /** @description User ID */
        id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Email verified successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid verification token */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_findAll: {
    parameters: {
      query?: {
        /** @description Items per page */
        limit?: number;
        /** @description Page number */
        page?: number;
        /** @description Filter workspaces */
        filter?: "owned" | "member" | "all";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspaces retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceDto"];
      };
    };
    responses: {
      /** @description Workspace created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_removeWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceDto"];
      };
    };
    responses: {
      /** @description Workspace updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_findMembers: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Members retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_updateMembersPrivilages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** @enum {string} */
          role?: "admin" | "member" | "viewer";
        };
      };
    };
    responses: {
      /** @description Member role updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid role */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_inviteMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateInvitationDto"];
      };
    };
    responses: {
      /** @description Invitation sent successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid email */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceController_acceptInvitation: {
    parameters: {
      query: {
        /** @description Invitation UUID */
        invitationId: string;
        /** @description Sender user UUID */
        senderId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation accepted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid invitation */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceMemberController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceMemberController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateWorkspaceMemberDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceMemberController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WorkspaceMemberController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateWorkspaceMemberDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BoardController_findAll: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Filter by board status */
        filter?: "all" | "archived" | "active";
      };
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Boards retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  BoardController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Workspace UUID */
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBoardDto"];
      };
    };
    responses: {
      /** @description Board created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Columns retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateColumnDto"];
      };
    };
    responses: {
      /** @description Column created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_findAll: {
    parameters: {
      query: {
        /** @description Number of items per page */
        limit: number;
        /** @description Page number */
        page: number;
        /** @description Filter by column ID */
        columnId?: string;
        /** @description Filter by assignee user ID */
        assigneeId?: string;
        /** @description Filter by priority */
        priority?: "low" | "medium" | "high" | "urgent";
        /** @description Filter by tag ID */
        tagId?: string;
        /** @description Filter tasks with due date from this date */
        dueDateFrom?: string;
        /** @description Filter tasks with due date to this date */
        dueDateTo?: string;
        /** @description Search term for task title/description */
        search?: string;
        /** @description Sort by field */
        sortBy?: "createdAt" | "dueDate" | "priority" | "updatedAt";
        /** @description Sort order (asc/desc) */
        sortOrder?: "ASC" | "DESC";
        /** @description Filter by task status */
        status?: string;
      };
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tasks retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Board not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_createTasks: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskDto"];
      };
    };
    responses: {
      /** @description Task created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_archiveBoard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Board archived successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_restoreBoard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Board restored successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_removeBoard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Board deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_updateBoard: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBoardDto"];
      };
    };
    responses: {
      /** @description Board updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
        /** @description Column UUID */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Column deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
        /** @description Column UUID */
        columnId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateColumnDto"];
      };
    };
    responses: {
      /** @description Column updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ColumnController_reOrderColumn: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Board UUID */
        boardId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReOrderColumnDto"];
      };
    };
    responses: {
      /** @description Columns reordered successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task details retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Task deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTaskDto"];
      };
    };
    responses: {
      /** @description Task updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_assignTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignUsersToTaskDto"];
      };
    };
    responses: {
      /** @description Users assigned successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid user IDs */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_unassignTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
        /** @description User UUID */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User unassigned successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task or user not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskController_moveTask: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveTaskDto"];
      };
    };
    responses: {
      /** @description Task moved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid column ID */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentController_findAll: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
      };
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comments retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommentDto"];
      };
    };
    responses: {
      /** @description Comment created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Comment UUID */
        commentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Comment deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  CommentController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Comment UUID */
        commentId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommentDto"];
      };
    };
    responses: {
      /** @description Comment updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attachments retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentController_create: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file?: string;
        };
      };
    };
    responses: {
      /** @description Attachment uploaded successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description File too large */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentController_downloadAttachment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Attachment UUID */
        attachmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File downloaded successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Attachment not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAttachmentDto"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AttachmentController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Attachment UUID */
        attachmentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Attachment deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Tags retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TagController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTagDto"];
      };
    };
    responses: {
      /** @description Tag created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid input data */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActivityController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateActivityDto"];
      };
    };
    responses: {
      /** @description Activity created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ActivityController_findAll: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
      };
      header?: never;
      path: {
        /** @description Task UUID */
        taskId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Activity log retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Task not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationController_markAllAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All notifications marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationController_markAsRead: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Notification UUID */
        notification_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification marked as read */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskAssigneeController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskAssigneeController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskAssigneeDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskTagsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskTagsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskTagDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskWatcherController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  TaskWatcherController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTaskWatcherDto"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  SearchController_globalSearch: {
    parameters: {
      query: {
        /** @description term to search with */
        query: string;
        /** @description id of the workspace that user wants to search for */
        workspaceId?: string;
        /** @description Filter by item type (task, comment, etc) */
        type?: "TASKS" | "BOARDS" | "ALL";
        /** @description page number of the search results */
        page?: number;
        /** @description can not be negative */
        limit?: number;
        /** @description Search query string */
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Search results retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid search query */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
